# Generated by Django 3.2.9 on 2021-11-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'ordering': ['-created_at'], 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AlterField(
            model_name='stories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='text',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='stories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категории'),
        ),
    ]
