# Generated by Django 3.2.9 on 2021-12-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='stories', to='main.Category', verbose_name='Категории'),
        ),
    ]
