# Generated by Django 3.2.9 on 2021-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
