# Generated by Django 3.2.9 on 2021-12-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stories_category'),
        ('main', '0005_category_slug'),
    ]

    operations = [
    ]
